workflow: ProduceListing
steps:
  - id: RegisterFarmer
    type: Behavior
    actor: Farmer
    output: FarmerID
  - id: PublishProduce
    type: Event
    depends_on: RegisterFarmer
    data:
      crop: Tomatoes
      quantity: 100kg
      location: [23.45, 77.11]